const API_LIFECYCLE_PROTOTYPED = "PROTOTYPED";
const API_ACCESSIBILTY_PROPERTY_KEY = "accessibility";
const API_ACCESSIBILTY_PROPERTY_VALUE_EXTENAL = "external";
const API_CREATE_APP_DEFAULT_THROTTLING_POLICY = "Unlimited";
const API_APPLICATION_SCOPE_ATTRINUTE_NAME = "scopes";