## The GraphQL schema. E.g., https://countries.trevorblades.com or ./schemas/country.graphql
schema: ./resources/schema.graphql
## The GraphQL documents that have queries/mutations
documents:
   - ./resources/query-project-apis.graphql